version: 2
jobs:
  build:
    docker:
      - image: hiroyukionaka/pandoc-lualatex-ja 
        steps:
          - checkout
          - run:
            name: Greeting
            command: echo Hello, world.
          - run:
            name: Print the Current Time
            command: date
          - run: 
            name: Compile TeX to PDF
            command: make all
