version: 2
jobs:
  build:
    docker:
      - image: hiroyukionaka/pandoc-lualatex-ja 
    working_directory: ~/wd
    steps:
      - checkout
      - run:
          name: Greeting
          command: echo Hello, world.
      - run:
          name: Print the Current Time
          command: date
      - run: 
          name: Compile TeX to PDF
          command: make all
      - save_cache: 
          key: build-{{ .Revision }}
          paths: 
            - ~/wd/build
  deploy:
    docker: 
      - image: circleci/golang
    working_directory: ~/wd
    steps:
        - run: 
            name: compile gdrive
            command: go get github.com/prasmussen/gdrive
        - restore_cache: 
            keys:
              - build-{{ .Revision }}
        - run: 
            name: send compiled manuscript
            command: | 
              echo $GOOGLE_SERVICE_ACCOUNT_CREDENTIAL > credential.json
              fname=eda_env_doc_$(date +%Y%m%d_%H%M%S).pdf && mv ~/wb/build/eda_env_doc.pdf ${fname}
              gdrive --config $(pwd) --service-account credential.json upload -p ${fname}
            
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
