# Reference: http://tech.quartetcom.co.jp/2018/05/14/markdown-pdf-circleci-googledrive-deployment/

version: 2
jobs:
  build:
    docker:
      - image: stomoki/luatexja_go
    working_directory: ~/wd
    steps:
      - checkout
      - run: 
          name: Compile TeX to PDF
          command: make all
      - save_cache: 
          key: build-{{ .Revision }}
          paths: 
            - build
  deploy:
    docker:
      - image: stomoki/luatexja_go
    working_directory: ~/wd
    steps:
        - run: 
            name: compile gdrive
            command: go get github.com/prasmussen/gdrive
        - run: 
            name: add directory
            command: mkdir build && chmod -R 777 build
        - run: 
            name: check pwd
            command: pwd && ls -lr
        - restore_cache: 
            keys:
              - build-{{ .Revision }}
        - deploy: 
            name: upload pdf
            command: | 
              echo $GOOGLE_SERVICE_ACCOUNT_CREDENTIAL > credential.json
              fname=eda_env_doc_$(date +%Y%m%d_%H%M%S).pdf && mv ~/wd/build/eda_env_doc.pdf ${fname}
              gdrive --config $(pwd) --service-account credential.json upload -p $TARGET_GDRIVE_DIR_ID ${fname}
            
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
