version: 2
jobs:
  build:
    docker:
      - image: hiroyukionaka/pandoc-lualatex-ja 
        #    working_directory: ~/wd
    steps:
      - checkout
      - run:
          name: Greeting
          command: echo Hello, world.
      - run:
          name: Print the Current Time
          command: date
      - run: 
          name: Compile TeX to PDF
          command: make all
      - save_cache: 
          key: build-{{ .Revision }}
          paths: 
            - ~/
          # - ~wd/build
  deploy:
    docker: 
      - image: circleci/golang
    steps:
        - run: go get github.com/prasmussen/gdrive
        - restore_cache: 
            keys:
              - build-{{ .Revision }}
        - deploy: 
          command: | 
             # 環境変数から認証情報を取得してJSONファイルに出力
             echo $GOOGLE_SERVICE_ACCOUNT_CREDENTIAL > credential.json
             #                         # 成果物のディレクトリ名を日時でリネーム
             fname=eda_env_doc_$(date +%Y%m%d_%H%M%S).pdf && mv build/eda_env_doc.pdf ${fname}
             #                                                 # 成果物のディレクトリを丸ごとデプロイ
             gdrive --config $(pwd) --service-account credential.json upload -p ${fname}
            
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
        requires:
          - build
